"""Public runtime API surface for experiment orchestration."""

from .contracts import (
    CoevConfig,
    GepaOptimizationConfig,
    GenerationRequest,
    GenerationSession,
    HarmbenchJudgeConfig,
    JudgeRuntime,
    LocalHFConfig,
    LoRABridge,
    ModelConfig,
    OpenAIReflectionConfig,
    OpenAITargetConfig,
    ReflectionGateway,
    TargetModelConfig,
    TargetRuntime,
    UnslothAdversaryConfig,
)
from .defaults import (
    apply_shared_generation_defaults,
    build_config_snapshot,
    deep_merge_runs,
    load_default_config,
    resolve_config_path,
    resolve_hf_token,
    scoped_env,
)
from .evaluation import EvaluationBatchResult, EvaluationConfig, EvaluatedSample, EvaluationResult, evaluate_examples, evaluate_outputs
from .openai_http import OpenAIReflectionGateway
from .gepa_prompt_optimization import (
    DualRoleGepaContext,
    DualRoleGepaOptimizationResult,
    DualRoleGepaPromptOptimizationConfig,
    GepaPromptOptimizationConfig,
    run_dual_role_gepa_prompt_optimization,
    run_gepa_prompt_optimization,
)
from .sessions import (
    RuntimeCatalog,
    build_local_hf_target_session,
    build_reflection_gateway_for_defaults,
    build_vllm_stack,
    build_vllm_target_session,
    cap_thread_workers,
    patch_run_args_from_config,
    resolve_reflection_env_overrides,
    run_target_requests_ordered,
    timed_target_generate,
)

__all__ = [
    "GenerationRequest",
    "GenerationSession",
    "HarmbenchJudgeConfig",
    "JudgeRuntime",
    "LocalHFConfig",
    "ModelConfig",
    "TargetModelConfig",
    "CoevConfig",
    "GepaOptimizationConfig",
    "LoRABridge",
    "OpenAIReflectionConfig",
    "OpenAITargetConfig",
    "OpenAIReflectionGateway",
    "ReflectionGateway",
    "RuntimeCatalog",
    "TargetRuntime",
    "UnslothAdversaryConfig",
    "EvaluationConfig",
    "EvaluationResult",
    "EvaluatedSample",
    "EvaluationBatchResult",
    "evaluate_examples",
    "evaluate_outputs",
    "GepaPromptOptimizationConfig",
    "DualRoleGepaPromptOptimizationConfig",
    "DualRoleGepaContext",
    "DualRoleGepaOptimizationResult",
    "run_gepa_prompt_optimization",
    "run_dual_role_gepa_prompt_optimization",
    "load_default_config",
    "apply_shared_generation_defaults",
    "deep_merge_runs",
    "build_config_snapshot",
    "resolve_config_path",
    "build_vllm_target_session",
    "build_vllm_stack",
    "build_local_hf_target_session",
    "build_reflection_gateway_for_defaults",
    "patch_run_args_from_config",
    "resolve_reflection_env_overrides",
    "resolve_hf_token",
    "scoped_env",
    "timed_target_generate",
    "cap_thread_workers",
    "run_target_requests_ordered",
]

